### ISSUE TITLE
Refreshing any page takes user back to login page, then to validations page

### ISSUE THREAD

**Issue by aidan-fitz** [covid19risk/permission-portal#136] opened 2020-05-23 02:30 UTC
When you refresh any page while logged in as the account admin, you are taken to the login page, then to the code validations page.

![Refresh horror](https://user-images.githubusercontent.com/2768977/82719787-bfbd8300-9c7b-11ea-902b-371be94d06b6.gif)

**Comment by ibeckermayer** [comment] 2020-05-27 02:20
I believe the cause/solution is described in more detail with https://github.com/covid19risk/permission-portal/issues/172 so I'm closing this one.

**Closed by ibeckermayer** 2020-05-27 02:20 UTC
