### ISSUE TITLE
New Member First Time Login - Welcome Modal UI and Change Password

### ISSUE THREAD

**Issue by therealnikhil** [covid19risk/permission-portal#104] opened 2020-05-17 18:01 UTC
![image](https://user-images.githubusercontent.com/16310780/82156025-d6f90c80-9846-11ea-822d-1a1e8b153a4c.png)

**Comment by ibeckermayer** [comment] 2020-05-17 19:30
This design doesn't work -- Firebase takes care of password resets for us.

Currently, when a new user signs up, the frontend should generate a random password and send it in the call to `createUser`. The created user will then get a password reset email sent to them, and click the link in there, which sends them to a firebase hosted reset page.

Note that the randomly generated pwd never needs to be known to anyone, its just a placeholder until the user goes through the reset flow to set their pwd. It's kept there since it was how the endpoint was originally designed before we'd nailed down the flow (easier to just keep it as is), and gives us the option to set user's passwords manually for testing purposes if we want to.

**Comment by ibeckermayer** [comment] 2020-05-18 19:55
Spoke with @joshlf and confirmed that this should happen eventually, but is not super high priority. Moving to post v3 because its relatively complex, involving lots of state.

**Comment by aidan-fitz** [comment] 2020-06-18 23:58
Looks like this was implemented in #241, so I'm closing it.

**Closed by aidan-fitz** 2020-06-18 23:58 UTC
